apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

namespace: streamforge-dev

patches:
- path: patch.yml
  target:
    kind: Namespace
    labelSelector: app.kubernetes.io/name=streamforge
    name: streamforge
    version: v1

replicas:
- count: 1
  name: sf-api
- count: 1
  name: sf-frontend
- count: 1
  name: sf-transcoder

images:
- name: ghcr.io/sudheerkumarp0357/streamforge/api
  newName: ghcr.io/sudheerkumarp0357/streamforge/api
  newTag: sha-c54dea49e5eb2eebe5147661d618897e4ad5e6a7
- name: ghcr.io/sudheerkumarp0357/streamforge/frontend
  newName: ghcr.io/sudheerkumarp0357/streamforge/frontend
  newTag: sha-53c4cdc1513980cf0eb2f3e59b18d91cc42b3d0d
- name: ghcr.io/sudheerkumarp0357/streamforge/transcoder
  newName: ghcr.io/sudheerkumarp0357/streamforge/transcoder
  newTag: sha-c54dea49e5eb2eebe5147661d618897e4ad5e6a7
