apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - azure-cosmos-db-secrets.yml
  - postgres-secrets.yml
  - common-secrets.yml
  - azure-storage-account-secrets.yml
