# --------- ConfigMap : Redis ---------
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-streamforge-redis
  namespace: streamforge
  labels:
    app: streamforge
    app.kubernetes.io/name: streamforge
    app.kubernetes.io/component: configmaps
data:
  redis-config: |
    maxmemory 100mb
    maxmemory-policy allkeys-lru
    appendonly yes

---
