---
# --------- Secrets : AzureStorgeAccount ---------
apiVersion: v1
data:
  AZURE_STORAGE_ACCOUNT_KEY: "VlZjT1NuL09Kbk1DZktWendJYmpaUHFpd0RTTWZoWGU0bWJvMDVOamZnL1BUeXBQR29rY0JwLzBKSm1QbnhnUWVyS2Zlc3Z4MGRkNCtBU3RHTFdBTnc9PQo="
  COSMOS_CONNECTION_STRING: ""
  JWT_SECRET: "c3VwZXItc2VjcmV0LWxvY2FsLWRldi1rZXktMTIzNDUK"
  POSTGRES_PASSWORD: "UGFzc3dvcmQwMzU3Cg=="
  RABBITMQ_URL: "YW1xcDovL3N0cmVhbWZvcmdlOnN0cmVhbWZvcmdlQHNmLXJhYmJpdG1xLXN2Yzo1NjcyLwo="
  RABBITMQ_DEFAULT_PASS: "UGFzc3dvcmQwMzU3Cg=="
  REDIS_PASSWORD: ""
kind: Secret
metadata:
  name: sf-secrets
  namespace: streamforge
  labels:
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/name: streamforge
    app.kubernetes.io/component: secrets
