# --------- ConfigMap : Redis ---------
apiVersion: v1
kind: ConfigMap
metadata:
  name: streamforge-redis-config
  labels:
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/component: configmaps
data:
  redis-config: |
    maxmemory 100mb
    maxmemory-policy allkeys-lru
    appendonly yes

---
