apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - ./storage/
  - ./configmaps/
  - ./secrets/
  - ./rabbitmq/
  - ./api/
  - ./transcoder/
  - ./frontend/
