---
# --------- Service : API ---------
apiVersion: v1
kind: Service
metadata:
  name: sf-api-svc
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
