apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sf-frontend
  namespace: argocd
  labels:
    name: frontend
    project: streamforge
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: streamforge
  source:
    repoURL: https://github.com/SudheerKumarP0357/streamforge.git
    targetRevision: HEAD
    path: gitops/manifests/frontend

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: streamforge-prod

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
  revisionHistoryLimit: 10
