# --------- Persistent Volume : Redis ---------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-streamforge-redis
  labels:
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/component: persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: streamforge
  hostPath:
    path: /streamforge/redis_data
