---
# --------- Namespace: streamforge ---------
apiVersion: v1
kind: Namespace
metadata:
  name: streamforge
  labels:
    app.kubernetes.io/component: namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
