apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: streamforge-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: streamforge-application
