apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-health-check
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: streamforge-infra
    app.kubernetes.io/component: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
    namespace: argocd
  default:
    interval: 10s
    timeout: 5s
    healthyThreshold: 2
    unhealthyThreshold: 3
    port: 8080
    http:
      path: /healthz
      match:
        statusCodes:
          - start: 200
            end: 299
    useTLS: false
