apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: streamforge-dev

patches:
  - path: namespace-patch.yml
    target:
      version: v1
      kind: Namespace
      name: streamforge
      labelSelector: "app.kubernetes.io/name=streamforge"

replicas:
  - name: streamforge-api
    count: 1
  - name: streamforge-frontend
    count: 1
