apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
data:
  NAMESPACE: streamforge-prod
  CLIENT_ID: "PLACEHOLDER_PROD_CLIENT_ID"
  TEANNT_ID: "92768f97-e40a-49b6-8fd5-a20497464fdc"
  KEY_VAULT_NAME: "kv-streamforgeprodci"
  RABBITMQ_DEFAULT_USER: "streamforge"
  POSTGRES_HOST: "PLACEHOLDER_PROD_POSTGRES_HOST"
  POSTGRES_USER: "streamforge"
  POSTGRES_DB: "streamforge"
  REDIS_HOST: "PLACEHOLDER_PROD_REDIS_HOST"
  REDIS_PORT: "10000"
  REDIS_URL: "PLACEHOLDER_PROD_REDIS_URL"
  AZURE_STORAGE_ACCOUNT_NAME: "PLACEHOLDER_PROD_STORAGE_ACCOUNT"
  AZURE_STORAGE_ENDPOINT: "PLACEHOLDER_PROD_STORAGE_ENDPOINT"
  CORS_ALLOWED_ORIGIN: "https://streamforge.sudheer.fun/"
