# --------- Storage Class: Azure Disk ---------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: streamforge-azure-csi
  labels:
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/name: streamforge
provisioner: disk.csi.azure.com
parameters:
  skuname: Standard_LRS
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
# --------- Persistent Volume Claim : Postgres ---------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-streamforge-postgres
  namespace: streamforge
  labels:
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/name: streamforge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: streamforge-azure-csi
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
---
# --------- Persistent Volume Claim : Redis ---------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-streamforge-redis
  namespace: streamforge
  labels:
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/name: streamforge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: streamforge-azure-csi
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem

---
# --------- Persistent Volume Claim : Redis ---------
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-streamforge-rabbitmq
#   labels:
#     app.kubernetes.io/part-of: streamforge-application
#     app.kubernetes.io/name: streamforge
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: streamforge-azure-csi
#   resources:
#     requests:
#       storage: 500Mi
#   volumeMode: Filesystem
