---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-sf
  labels:
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/component: secret-provider-class
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "PLACEHOLDER_CLIENT_ID"
    keyvaultName: "PLACEHOLDER_KEYVAULT_NAME"
    cloudName: "AzurePublicCloud"
    tenantID: "PLACEHOLDER_TENANT_ID"
    objects: |
      array:
        - |
          objectName: rabbitmq-url
          objectType: secret
        - |
          objectName: rabbitmq-default-pass
          objectType: secret
        - |
          objectName: azure-storage-account-key
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: cosmos-connection-string
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret

  secretObjects:
    - secretName: sf-secrets
      type: Opaque
      labels:
        app.kubernetes.io/part-of: streamforge-application
        app.kubernetes.io/component: secrets
      data:
        - objectName: rabbitmq-url
          key: RABBITMQ_URL

        - objectName: rabbitmq-default-pass
          key: RABBITMQ_DEFAULT_PASS

        - objectName: azure-storage-account-key
          key: AZURE_STORAGE_ACCOUNT_KEY

        - objectName: postgres-password
          key: POSTGRES_PASSWORD

        - objectName: cosmos-connection-string
          key: COSMOS_CONNECTION_STRING

        - objectName: redis-password
          key: REDIS_PASSWORD

        - objectName: jwt-secret
          key: JWT_SECRET
