apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: streamforge-dev

generatorOptions:
  disableNameSuffixHash: true

patches:
  # ── cert-manager: ClusterIssuer email ──────────────────────────────────────
  - path: patches/issuer-patch.yml
    target:
      group: cert-manager.io
      version: v1
      kind: ClusterIssuer
      name: cloudflare-cluster-issuer

  # ── cert-manager: Certificate domains ─────────────────────────────────────
  - path: patches/certificate-patch.yml
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: streamforge-tls-cert

  # ── Gateway: hostname + ALB annotations ───────────────────────────────────
  - path: patches/gateway-patch.yml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: streamforge-gateway

  # ── HTTPRoute: hostnames ───────────────────────────────────────────────────
  - path: patches/httproute-patch.yml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: http-to-https-redirect

  # ── Frontend HTTPRoute: hostnames ───────────────────────────────────────────
  - path: patches/frotend-httproute-patch.yml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: frontend-httproute
