---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-sf
  labels:
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/component: secret-provider-class
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "f889c917-bb1a-4f76-934d-8048eddbf655"
    keyvaultName: "kv-streamforgeprodci"
    cloudName: "AzurePublicCloud"
    tenantID: "92768f97-e40a-49b6-8fd5-a20497464fdc"
    objects: |
      array:
        - |
          objectName: rabbitmq-url
          objectType: secret
        - |
          objectName: rabbitmq-default-pass
          objectType: secret
        - |
          objectName: rabbitmq-default-user
          objectType: secret
        - |
          objectName: azure-storage-account-key
          objectType: secret
        - |
          objectName: azure-storage-account-name
          objectType: secret
        - |
          objectName: azure-storage-blob-endpoint
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-host
          objectType: secret
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-database
          objectType: secret
        - |
          objectName: cosmos-connection-string
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
        - |
          objectName: redis-hostname
          objectType: secret
        - |
          objectName: redis-url
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret

  secretObjects:
    - secretName: sf-secrets
      type: Opaque
      labels:
        app.kubernetes.io/part-of: streamforge-application
        app.kubernetes.io/component: secrets
      data:
        - objectName: rabbitmq-url
          key: RABBITMQ_URL

        - objectName: rabbitmq-default-pass
          key: RABBITMQ_DEFAULT_PASS

        - objectName: rabbitmq-default-user
          key: RABBITMQ_DEFAULT_USER

        - objectName: azure-storage-account-name
          key: AZURE_STORAGE_ACCOUNT_NAME

        - objectName: azure-storage-account-key
          key: AZURE_STORAGE_ACCOUNT_KEY

        - objectName: azure-storage-blob-endpoint
          key: AZURE_STORAGE_ENDPOINT

        - objectName: postgres-password
          key: POSTGRES_PASSWORD

        - objectName: postgres-host
          key: POSTGRES_HOST

        - objectName: postgres-user
          key: POSTGRES_USER

        - objectName: postgres-database
          key: POSTGRES_DB

        - objectName: cosmos-connection-string
          key: COSMOS_CONNECTION_STRING

        - objectName: redis-password
          key: REDIS_PASSWORD

        - objectName: redis-hostname
          key: REDIS_HOST

        - objectName: redis-url
          key: REDIS_URL

        - objectName: jwt-secret
          key: JWT_SECRET
