---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sf-configmaps
data:
  RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_SSL_MODE: require
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: "10000"
  REDIS_URL: rediss://${REDIS_HOST}:${REDIS_PORT}
  RABBITMQ_PORT: "5672"
  RABBITMQ_HOST: sf-rabbitmq-svc
  AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
  AZURE_STORAGE_ENDPOINT: https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/
  AZURE_BLOB_RAW_CONTAINER: raw-videos
  AZURE_BLOB_HLS_CONTAINER: hls-videos
  COSMOS_DATABASE: streamforge
  JWT_EXPIRY_HOURS: "24"
  REFRESH_TOKEN_EXPIRY_DAYS: "7"
  CORS_ALLOWED_ORIGIN: https://streamforge.sudheer.fun/
  FFMPEG_PATH: /usr/bin/ffmpeg
  TEMP_DIR: /tmp
