apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

namespace: streamforge-dev

patches:
- path: patch.yml
  target:
    kind: Namespace
    labelSelector: app.kubernetes.io/name=streamforge
    name: streamforge
    version: v1

replicas:
- count: 1
  name: sf-api
- count: 1
  name: sf-frontend
- count: 1
  name: sf-transcoder

images:
- name: ghcr.io/sudheerkumarp0357/streamforge/api
  newName: ghcr.io/sudheerkumarp0357/streamforge/api
  newTag: sha-3f25ca12558a769a3765cfc1fb99e4e3e8e55977
- name: ghcr.io/sudheerkumarp0357/streamforge/frontend
  newName: ghcr.io/sudheerkumarp0357/streamforge/frontend
  newTag: sha-c54dea49e5eb2eebe5147661d618897e4ad5e6a7
- name: ghcr.io/sudheerkumarp0357/streamforge/transcoder
  newName: ghcr.io/sudheerkumarp0357/streamforge/transcoder
  newTag: sha-transcoder
