apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yml
  - argocd-httproute.yml
  - httproute.yml
  - certificate.yml
  - alb-argocd-health-check-policy.yml
  - argocd-values.yaml
