# --------- Service : Postgres ---------
apiVersion: v1
kind: Service
metadata:
  name: streamforge-postgres-svc
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: streamforge-application
    app.kubernetes.io/component: database
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
