name: Backend API CI

on:
  push:
    branches:
      - pipelines
      # - "main"

    paths:
      # - "backend/api/**"
  # pull_request:
  #   branches:
  #     # - "main"
  #   paths:
  #     # - "backend/api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/api
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.0"
          cache-dependency-path: backend/api/go.sum

      - name: Build API
        run: go build -mod=readonly -v ./...
        working-directory: ./backend/api

      - name: Go Vet
        run: go vet ./...
        working-directory: ./backend/api

  docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Docker Build & Push
        with:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
          ARTIFACT_NAME: api
          CONTEXT_PATH: ./backend/api
          DOCKERFILE_NAME: Dockerfile
