---
name: Streamforge Frontend CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ARTIFACT_NAME: frontend

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 24.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 24.11.0
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build the Frontend

  docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-frontend

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: ./.github/actions/docker-build-push
        with:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
          ARTIFACT_NAME: frontend
          CONTEXT_PATH: ./frontend
          DOCKERFILE_NAME: Dockerfile
          PUSH_TO_REGISTRY: ${{ github.event_name == 'push' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
