name: KeyVault Secrets Updater

on:
  workflow_run:
    workflows: ["Infra Provision - Azure"]
    types:
      - completed
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_USE_AZUREAD: true
  ARM_USE_OIDC: true

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  provision-secrets:
    name: Provision KeyVault Secrets
    defaults:
      run:
        working-directory: ./infra/secrets

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Download Terraform Output
        uses: actions/download-artifact@v4
        with:
          name: key-vault-secrets
          path: infra/secrets
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Export Variables
        run: |
          while IFS='=' read -r key value; do
            echo "$key=$value" >> $GITHUB_ENV
          done < key_vault_secrets_data.txt

      - name: Get Runner IP
        id: runner_ip
        run: echo "ip=$(curl -s ifconfig.me/ip)" >> $GITHUB_OUTPUT

      - name: Temporarily Open Keyvault to public
        id: open_kv
        run: |
          az keyvault update --name ${TF_VAR_key_vault_name} --public-network-access Enabled
          az keyvault network-rule add \
            --name ${TF_VAR_key_vault_name} \
            --ip-address ${{ steps.runner_ip.outputs.ip }} \
            --resource-group ${TF_VAR_resource_group_name}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.BACKEND_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.KV_BACKEND_KEY }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=secrets.tfplan

      - uses: trstringer/manual-approval@v1
        name: Review and Approve KeyVault Secrets
        with:
          secret: ${{ github.TOKEN }}
          approvers: SudheerKumarP0357
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Terraform Apply"
          issue-body: "Please approve or deny the deployment."
          fail-on-denial: true

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve secrets.tfplan

      - name: Close Keyvault to public
        if: always()
        run: |
          az keyvault update --name ${TF_VAR_key_vault_name} --public-network-access Disabled
          az keyvault network-rule remove \
            --name ${TF_VAR_key_vault_name} \
            --ip-address ${{ steps.runner_ip.outputs.ip }} \
            --resource-group ${TF_VAR_resource_group_name}
