name: Primary Workflow

on: [workflow_dispatch]

jobs:
  primary-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: create-text-file
        run: |
          export NAME=Sudheer
          export EVENT_NAME=${{ github.event_name }}
          echo "NAME=${NAME}" >> values.txt
          echo "EVENT_NAME=${EVENT_NAME} >> values.txt
      - name: Upload values.txt
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: values.txt
          path: values.txt
          retention-days: 1
