name: Secondary Workflow

on: 
 workflow_run:
   workflows: [Primary Workflow]
   types: completed

jobs:
  secondary-workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download values.txt
        uses: actions/download-artifact@v4
        with:
          name: values
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      
      - name: Print the values
        run: cat values.txt
